<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="10" total="18" passed="0" failed="7" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[Testing all Assertions]]>
    </line>
    <line>
      <![CDATA[Testing String iteration-1]]>
    </line>
    <line>
      <![CDATA[Testing boolean iteration-2]]>
    </line>
    <line>
      <![CDATA[Testing null iteration-2]]>
    </line>
    <line>
      <![CDATA[Testing all Assertions]]>
    </line>
    <line>
      <![CDATA[Method-3]]>
    </line>
  </reporter-output>
  <suite started-at="2021-06-11T02:35:57Z" name="Failed suite [testNGSuite]" finished-at="2021-06-11T02:35:57Z" duration-ms="127">
    <groups>
      <group name="Functional">
        <method signature="testNGKeywords.method3()[pri:49, instance:tesNGBasics.testNGKeywords@7a52f2a2]" name="method3" class="tesNGBasics.testNGKeywords"/>
        <method signature="testNGKeywords.method5()[pri:0, instance:tesNGBasics.testNGKeywords@7a52f2a2]" name="method5" class="tesNGBasics.testNGKeywords"/>
      </group> <!-- Functional -->
      <group name="Sanity">
        <method signature="testNGKeywords.method3()[pri:49, instance:tesNGBasics.testNGKeywords@7a52f2a2]" name="method3" class="tesNGBasics.testNGKeywords"/>
        <method signature="testNGKeywords.method5()[pri:0, instance:tesNGBasics.testNGKeywords@7a52f2a2]" name="method5" class="tesNGBasics.testNGKeywords"/>
      </group> <!-- Sanity -->
    </groups>
    <test started-at="2021-06-11T02:35:57Z" name="testNGTest(failed)" finished-at="2021-06-11T02:35:57Z" duration-ms="127">
      <class name="tesNGBasics.testNGKeywords">
        <test-method signature="method3()[pri:49, instance:tesNGBasics.testNGKeywords@7a52f2a2]" started-at="2021-06-11T02:35:57Z" name="method3" finished-at="2021-06-11T02:35:57Z" duration-ms="3" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at tesNGBasics.testNGKeywords.method3(testNGKeywords.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Method-3]]>
            </line>
          </reporter-output>
        </test-method> <!-- method3 -->
        <test-method signature="method5()[pri:0, instance:tesNGBasics.testNGKeywords@7a52f2a2]" started-at="2021-06-11T02:35:57Z" name="method5" finished-at="2021-06-11T02:35:57Z" depends-on-methods="tesNGBasics.testNGKeywords.method3" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method testNGKeywords.method5()[pri:0, instance:tesNGBasics.testNGKeywords@7a52f2a2] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method testNGKeywords.method5()[pri:0, instance:tesNGBasics.testNGKeywords@7a52f2a2] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method5 -->
      </class> <!-- tesNGBasics.testNGKeywords -->
      <class name="tesNGBasics.testNGAssertions">
        <test-method signature="test8()[pri:0, instance:tesNGBasics.testNGAssertions@69930714]" started-at="2021-06-11T02:35:57Z" name="test8" finished-at="2021-06-11T02:35:57Z" duration-ms="17" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.assertNotNull(Assert.java:686)
at org.testng.Assert.assertNotNull(Assert.java:671)
at tesNGBasics.testNGAssertions.test8(testNGAssertions.java:90)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Testing all Assertions]]>
            </line>
          </reporter-output>
        </test-method> <!-- test8 -->
        <test-method signature="test4()[pri:0, instance:tesNGBasics.testNGAssertions@69930714]" started-at="2021-06-11T02:35:57Z" name="test4" finished-at="2021-06-11T02:35:57Z" duration-ms="19" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at tesNGBasics.testNGAssertions.test4(testNGAssertions.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Testing boolean iteration-2]]>
            </line>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method signature="test1()[pri:0, instance:tesNGBasics.testNGAssertions@69930714]" started-at="2021-06-11T02:35:57Z" name="test1" finished-at="2021-06-11T02:35:57Z" duration-ms="12" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Hello> but was:<Hi>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Hello> but was:<Hi>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
at tesNGBasics.testNGAssertions.test1(testNGAssertions.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Testing String iteration-1]]>
            </line>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method signature="test9()[pri:0, instance:tesNGBasics.testNGAssertions@69930714]" started-at="2021-06-11T02:35:57Z" name="test9" finished-at="2021-06-11T02:35:57Z" duration-ms="60" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected object to not be null
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at tesNGBasics.testNGAssertions.test9(testNGAssertions.java:109)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Testing all Assertions]]>
            </line>
          </reporter-output>
        </test-method> <!-- test9 -->
        <test-method signature="test7()[pri:0, instance:tesNGBasics.testNGAssertions@69930714]" started-at="2021-06-11T02:35:57Z" name="test7" finished-at="2021-06-11T02:35:57Z" duration-ms="20" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at tesNGBasics.testNGAssertions.test7(testNGAssertions.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Testing null iteration-2]]>
            </line>
          </reporter-output>
        </test-method> <!-- test7 -->
      </class> <!-- tesNGBasics.testNGAssertions -->
      <class name="tesNGBasics.test1Class">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:tesNGBasics.test1Class@a4102b8]" started-at="2021-06-11T02:35:57Z" name="beforeSuite" finished-at="2021-06-11T02:35:57Z" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:tesNGBasics.test1Class@a4102b8]" started-at="2021-06-11T02:35:57Z" name="beforeTest" finished-at="2021-06-11T02:35:57Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:tesNGBasics.test1Class@a4102b8]" started-at="2021-06-11T02:35:57Z" name="beforeClass" finished-at="2021-06-11T02:35:57Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:tesNGBasics.test1Class@a4102b8]" started-at="2021-06-11T02:35:57Z" name="beforeMethod" finished-at="2021-06-11T02:35:57Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="method3()[pri:0, instance:tesNGBasics.test1Class@a4102b8]" started-at="2021-06-11T02:35:57Z" name="method3" finished-at="2021-06-11T02:35:57Z" duration-ms="36" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at tesNGBasics.test1Class.method3(test1Class.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method3 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:tesNGBasics.test1Class@a4102b8]" started-at="2021-06-11T02:35:57Z" name="afterMethod" finished-at="2021-06-11T02:35:57Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:tesNGBasics.test1Class@a4102b8]" started-at="2021-06-11T02:35:57Z" name="afterClass" finished-at="2021-06-11T02:35:57Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:tesNGBasics.test1Class@a4102b8]" started-at="2021-06-11T02:35:57Z" name="afterTest" finished-at="2021-06-11T02:35:57Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:tesNGBasics.test1Class@a4102b8]" started-at="2021-06-11T02:35:57Z" name="afterSuite" finished-at="2021-06-11T02:35:57Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- tesNGBasics.test1Class -->
    </test> <!-- testNGTest(failed) -->
  </suite> <!-- Failed suite [testNGSuite] -->
</testng-results>
