<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-CUU290R" failures="7" tests="19" name="testNGTest" time="0.271" errors="0" timestamp="11 Jun 2021 02:27:27 GMT">
  <testcase classname="tesNGBasics.testNGKeywords" name="method6" time="0.012"/>
  <testcase classname="tesNGBasics.testNGKeywords" name="method1" time="0.013"/>
  <testcase classname="tesNGBasics.testNGKeywords" name="method2" time="0.018"/>
  <testcase classname="tesNGBasics.testNGKeywords" name="method2" time="0.007"/>
  <testcase classname="tesNGBasics.testNGKeywords" name="method2" time="0.003"/>
  <testcase classname="tesNGBasics.test1Class" name="method2" time="0.004"/>
  <testcase classname="tesNGBasics.test1Class" name="method1" time="0.032"/>
  <testcase classname="tesNGBasics.test1Class" name="method3" time="0.016">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at tesNGBasics.test1Class.method3(test1Class.java:58)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- method3 -->
  <testcase classname="tesNGBasics.testNGAssertions" name="test3" time="0.02"/>
  <testcase classname="tesNGBasics.testNGAssertions" name="test4" time="0.027">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at tesNGBasics.testNGAssertions.test4(testNGAssertions.java:51)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="tesNGBasics.testNGAssertions" name="test1" time="0.067">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Hello&amp;gt; but was:&amp;lt;Hi&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Hello> but was:<Hi>
at tesNGBasics.testNGAssertions.test1(testNGAssertions.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="tesNGBasics.testNGAssertions" name="test5" time="0.045"/>
  <testcase classname="tesNGBasics.testNGAssertions" name="test6" time="0.03"/>
  <testcase classname="tesNGBasics.testNGAssertions" name="test7" time="0.011">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at tesNGBasics.testNGAssertions.test7(testNGAssertions.java:79)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- test7 -->
  <testcase classname="tesNGBasics.testNGAssertions" name="test8" time="0.018">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at tesNGBasics.testNGAssertions.test8(testNGAssertions.java:90)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- test8 -->
  <testcase classname="tesNGBasics.testNGAssertions" name="test9" time="0.015">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected object to not be null">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected object to not be null
at tesNGBasics.testNGAssertions.test9(testNGAssertions.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- test9 -->
  <testcase classname="tesNGBasics.testNGKeywords" name="method3" time="0.003">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at tesNGBasics.testNGKeywords.method3(testNGKeywords.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- method3 -->
  <testcase classname="tesNGBasics.testNGKeywords" name="method5" time="0.0">
    <skipped/>
  </testcase> <!-- method5 -->
  <testcase classname="tesNGBasics.testNGKeywords" name="method4" time="0.004"/>
  <testcase classname="tesNGBasics.testNGAssertions" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
</testsuite> <!-- testNGTest -->
